version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-inventory-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DATABASE_NAME: books_py_db
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - book-network

  mongodb:
    image: mongo:7.0
    container_name: book-inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - book-network

volumes:
  mongo_data:

networks:
  book-network:
    driver: bridge