apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: fastapi-books-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
            - name: DATABASE_NAME
              value: "books_py_db"