apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  MONGO_URI: {{ .Values.env.mongoUri | b64enc | quote }}
  DATABASE_NAME: {{ .Values.env.databaseName | b64enc | quote }}