apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}-deployment
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}-container
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.databaseName | quote }}
          resources:
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
              memory: {{ .Values.mongodb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
              memory: {{ .Values.mongodb.resources.limits.memory }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.name }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}