app:
  name: book-inventory-service
  replicas: 2
  image:
    repository: book-inventory-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mongodb:
  name: mongodb
  replicas: 1
  image: mongo:7.0
  port: 27017
  databaseName: books_py_db
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  storage: 1Gi

env:
  mongoUri: mongodb://mongodb:27017
  databaseName: books_py_db